###Register a user to the system
POST http://localhost:3002/register HTTP/1.1
Content-Type: application/json

{
    "name": "testing_user",
    "email": "test_user@gmail.com",
    "pwdhash": "password"
}

###Login to get auth id
POST http://localhost:3002/login HTTP/1.1
Content-Type: application/json

{
    "email": "test_user@gmail.com",
    "pwdhash": "password"
}

###Post Question
POST http://localhost:3002/questions?auth_id=30b5f10f-77ff-4c58-a204-0d9820bc9b5b HTTP/1.1
Content-Type: application/json

{
    "user_id": 2,
    "questions": "What is front end?"

}

###Get all Questions
GET http://localhost:3002/questions
Content-Type: application/json


###Post Comment to Question
POST http://localhost:3002/addcomment?auth_id=30b5f10f-77ff-4c58-a204-0d9820bc9b5b HTTP/1.1
Content-Type: application/json

{
    "user_id": 2,
    "question_id": 1,
    "comment": "A good question"

}


###Delete User's Question
DELETE http://localhost:3002/question/4 HTTP/1.1