###Register a user to the system
POST http://localhost:3002/register HTTP/1.1
Content-Type: application/json

{
    "first_name": "testing_user",
    "last_name":  "test_12",
    "email": "test_user@gmail.com",
    "user_name": "test_user",
    "password": "password",
    "confirm_password": "password",
    "sex": "male"
}

###Login to get auth id
POST http://localhost:3002/login HTTP/1.1
Content-Type: application/json

{
    "email": "test_user@gmail.com",
    "pwdhash": "password"
}

###Post Question
POST http://localhost:3002/questions?auth_id=c4a4055a-4235-4f24-9d1f-9a443751583c HTTP/1.1
Content-Type: application/json

{
    "questions": "What is the calucation?"

}

###Get all Questions
GET http://localhost:3002/questions
Content-Type: application/json

###Get Single Question
GET http://localhost:3002/questions/3d3794f5-0098-420a-b245-ee8b1c89088e
Content-Type: application/json

###Delete a sing user
DELETE http://localhost:3002/deleteuser?user_name=segun_1001
Content-Type: application/json


###Post Comment to Question
POST http://localhost:3002/addcomment?auth_id=e829d57a-7e59-43b4-b255-8f748e1276fd HTTP/1.1
Content-Type: application/json

{
    "question_id": "800ec3d6-3034-4e9e-b607-5fad1cf9aeab",
    "comment": "A good question"

}


###Delete User's Question
DELETE http://localhost:3002/question/c4707b91-6b0a-41b8-af07-2f3c291e2559?auth_id=e829d57a-7e59-43b4-b255-8f748e1276fd HTTP/1.1